//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AntennaHousePdf
{
    using System;
    using System.Collections.Generic;

    [System.ComponentModel.DataAnnotations.MetadataType(typeof(UserProfileMetadata))]
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

    
    internal sealed class UserProfileMetadata
    {
        [Required(ErrorMessage = "UserName is required.")]
        public string UserName;
        [Required(ErrorMessage = "Password is required.")]
        public string Password;
    }
}
